source: /src/
collections_config:
  pages:
    path: ''
    name: Pages
    icon: wysiwyg
  contact:
    path: contact
    name: Contact
    icon: contacts
  newsletter:
    path: newsletter
    name: Newsletter
    icon: newspaper
  posts:
    path: posts
    name: Posts
    icon: event_available
  recurse:
    path: recurse
    name: Recurse
    icon: close
  work:
    path: work
    name: Work
    icon: work
paths:
  static: ''
  uploads: uploads
timezone: America/New_York
markdown:
  engine: commonmark
  options:
    html: true
